export const eng = {
  km:'km',
  min:'min',
  back:'Back',
  jan: 'jan',
  fab: 'fab',
  march: 'march',
  apr: 'apr',
  may: 'may',
  june: 'june',
  july: 'july',
  aug: 'aug',
  sep: 'sep',
  oct: 'oct',
  nov: 'nov',
  dec: 'dec',
  hour:'h',
  noRide:'No Ride',
  fillEmail:'Fill in an e-mail',
  negativeBalance: 'Neg. balance',
  error: 'Error',
  close: 'Close',
  allowCamera: 'Turn on your camera, please',
  allow: 'Allow',
  arrorAddingCard: 'Error adding map',
  howParkText: 'We\'re committed to keeping the city lean and tidy. We ask you to do the same and verify it by taking a photo of your parking. Don\'t block pathways, entrances, or bike lanes. Try to park near bike racks or designated parking areas painted on the street. Frequent violation of our parking guidelines we result in an extra charge or even deactivation of your account.',
  inputPhoneNumber: 'Input phone number',
  invalidPhoneNumber: 'Invalid number',
  continue: 'Continue',
  continueWith: 'Or continue with',
  terms: 'If you create a new account, you automatically agree to the Terms of Use and Personal Data Protection',
  enterSms: 'Enter the code from the confirmation SMS',
  sentSms: 'We sent an SMS confirmation code to the phone number',
  resendCodeIn: 'Resend code in',
  resendCode: 'Resend code',
  resendSmsCode: 'Resend the SMS code',
  requestCall: 'Request a call',
  changePhoneNumber: 'Change the phone number',
  invalidSms: 'Invalid code',
  tellAboutYou: 'Tell us something about you',
  whatsYourName: 'What is your name?',
  name: 'Name',
  surname: 'Surname',
  incorrectName: 'The name you entered was incorrect',
  incorrectSurName: 'The surname you entered was incorrect',
  enterEmail: 'Enter your email',
  enterValidEmail: 'Please enter a valid email address',
  invalidEmail: 'The email you entered is invalid',
  ageSure: 'We need to be sure of the age',
  must18: 'You can use scooters only when you are 18+ years old',
  able18: 'You must be at least 18 years old to be able to ride around the town.',
  loading: 'Loading',
  addPaymentCard: 'Add a payment card',
  cardNumber: 'Card number',
  expiryDate: 'Expiry date',
  cvv: 'CVV',
  safetyComesFirst: 'Safety comes first',
  noScooterExperience: 'If you have no experience with electric scooters, we recommend choosing the "Beginner" mode with limited speed. You can reset this setting to the default 25 km/h at any time in the Safety Center.',
  beginner: 'Beginner',
  limitSpeed15: 'Limit speed to 15 km/h',
  notNow: 'Not now',
  safetyCenter: 'Safety Center',
  setPreferences: 'Set your preferences and get tips for safe driving!',
  scan: 'Scan',
  turnOnLocation: 'Turn on your location',
  withoutLocation: 'Without active geolocation functional applications will not be complete',
  iUnderstand: 'I understand',
  withoutAccessToFiles: 'Without access to files the application will not work',
  freeRide: 'Free ride on us!',
  checkPromoForFreeRide: 'Check your promo for free ride',
  weAreNotInCity: 'Oh, we are not in your city yet!',
  preparingToLaunchServiceInCity: 'We are just preparing to launch the service in your city. We\'ll let you know when that changes!',
  becomePartner: 'Become a partner',
  connectionLost: 'Connection lost. Try again.',
  wantKnowMoreAboutGettingStarted: 'I want to know more about getting started',
  safetyTips: 'Safety tips',
  learnMoreAboutRoadSafety: 'Learn more about road safety',
  localRules: 'Local rules',
  learnMoreAboutLocalRequirements: 'Learn more about the local requirements',
  privateRide: 'Private ride',
  corporateRide: 'Corporate ride',
  reserve: 'Reserve',
  unlock: 'Unlock',
  reserveFor: 'Reserve for',
  canReserveScooterForMinutes: 'You can reserve a scooter for',
  canReserveScooterForMinutes2: 'Billing will start as soon as you confirm the reservation.',
  confirmReservation: 'Confirm reservation',
  reservationOngoing: 'Reservation ongoing',
  cancelReservation: 'Cancel reservation',
  reservationCanceled: 'Reservation canceled',
  reservationTimedOut: 'Reservation timed out',
  reserveAgain: 'Reserve again',
  addCard: 'Add a card',
  skip: 'Skip',
  beforeYourRide: 'Before your ride',
  enterYourCardDetails: 'Enter your card details to start the ride.',
  drivingInProhibitedZone: 'You have entered restricted zone. You will not find a parking spot here',
  dangerDriving:'Driving in a prohibited zone',
  prohibitedZone: 'Prohibited zone!',
  endRide: 'End ride',
  startRide: 'Start a ride',
  thisIsParkingZone: 'This is parking zone',
  parkingAreaLook: 'Here you can see what the parking area looks like. Please find one nearby.',
  goParkingZone: 'Go to the parking zone!',
  endRideParkingZones: 'You can only end your ride in a designated parking zones.',
  enterCodeManually: 'Enter the code manually',
  scanError: 'Scan error. Please try again.',
  enterCodeToUnlock: 'Enter the code to unlock',
  scooterReadyEnterCode: 'Scooter is ready! Enter code (code on the steering wheel)',
  invalidCode: 'Invalid code, please try again.',
  activeRide: 'Active ride',
  slowZone: 'Slow zone',
  pauseRide: 'Pause ride?',
  pauseTemporarilyLock: 'Pause will temporarily lock the scooter so you can continue your ride later. The pause rate is applied for the duration of the lock.',
  pause: 'Pause',
  connectionError: 'Connection error',
  parkingZone: 'Parking zone',
  PausedRide: 'Paused ride',
  continueWithRide: 'Continue with ride',
  checkScooter: 'Check the scooter',
  scooterOnKickstand: 'The scooter is on the kickstand',
  scooterNotObstruct: 'The scooter does not obstruct cyclists, entrances, or roads',
  takePictureScooter: 'Take a picture of the scooter',
  howPark: 'How to park?',
  watchOutParking: 'Watchout for your parking!',
  yourRideHasEnded: 'Your ride has ended',
  pickUp: 'Pick up',
  badRide: 'Bad ride',
  goodRide: 'Good ride',
  reportProblem: 'Report a problem',
  somethingIsWrong: 'Something is wrong? Let`s look at it together. What is the problem about?',
  parking: 'Parking',
  scooter: 'Scooter',
  accident: 'Accident',
  app: 'App',
  contactUs: 'Contact us',
  parkingProblems: 'Parking problems',
  tellMoreAboutIssue: 'Tell us a little more about the issue…',
  scooterIsNotHere: 'Scooter is not here',
  scooterParkedIncorrectly: 'Scooter is parked incorrectly',
  scooterBlockingTraffic: 'Scooter is blocking traffic',
  others: 'Others',
  scooterNotWorkingTellAboutIssue: 'Scooter is not working? Tell us a little more about the issue…',
  scooterDamaged: 'Scooter is scratched or damaged',
  scooterTechnicalIssue: 'Scooter has technical issue',
  scooterTooSlow: 'Scooter is too slow',
  appSaysScooterOffline: 'App says scooter is offline',
  scooterNotResponding: 'Scooter is not responding',
  scooterDoesntStart: 'Scooter doesn’t start',
  scooterLayingGround: 'Scooter is laying on the ground',
  accidentHappenedTellAboutIssue: 'Accident happened? Tell us a little more about the issue…',
  iInvolvedInAccident: 'I was involved in an accident',
  iDamagedScooter: 'I scratched / damaged the scooter',
  appNotWorkTellAboutIssue: 'The app doesn\'t work as it should? Tell us a little more about the issue…',
  unableStartTrip: 'Unable to start the trip',
  unableEndTrip: 'Unable to end the trip',
  myAccountBlocked: 'My account is blocked',
  appCrashing: 'App is freezing or crashing',
  cantAddCard: 'I can’t add the card',
  reportDamage: 'Report damage',
  takePictureDamage: 'Take a picture of the damage',
  yourComment: 'Your comment (required)',
  enterProblemHere: 'Enter your problem here…',
  goToProfile: 'Go to profile',
  payment: 'Payment',
  promoCodes: 'Promo codes',
  freeMinutes: 'Free minutes',
  minutes:'minutes',
  claim: 'Claim',
  history: 'History',
  support: 'Support',
  partnership: 'Partnership',
  rewards: 'Rewards',
  personalInfo: 'Personal info',
  necessaryInfo: 'Necessary info',
  termsService: 'Terms of Service',
  personalDataProtectionPolicy: 'Personal data protection policy',
  aboutApplication: 'About application',
  areYouSureAboutChanges: 'Are you sure about changes?',
  problemWeCantSolveContactSupport: 'Do you have a problem that we can\'t solve in the app? Contact our support',
  questionsAndAnswers: 'Questions and Answers',
  safety: 'Safety',
  phone: 'Phone',
  chat: 'Chat',
  tellProblem: 'Tell us the problem',
  haveProblemTakeLookFAQ: 'Do you have a problem or question? Take a look at the FAQ.',
  historyOfRides: 'History of rides',
  historyOfPromoCodes: 'History of promo codes',
  scooterWillSlowDown: 'Your scooter will slow down and may stop сompletely. You can’t end your ride here. Please find a parking spot.',
  thankForRegistration: 'Thank you for your registration. We have a present for you! ',
  welcomeToSvist: 'Welcome to Svist! Please follow the tutorial to learn how to ride our scooter.',
  exit: 'Exit'

}
export const ukr = {
  km:'км',
  min:'хв',
  back:'Назад',
  jan: 'січ.',
  fab: 'лют.',
  march: 'берез.',
  apr: 'квіт.',
  may: 'трав.',
  june: 'черв.',
  july: 'лип.',
  aug: 'серп.',
  sep: 'верес.',
  oct: 'жовт.',
  nov: 'лист.',
  dec: 'груд.',
  hour:'год',
  noRide:'Їздити заборонено',
  fillEmail:'Заповніть електронну пошту',
  negativeBalance: 'Нег. баланс',
  error: 'Помилка',
  close: 'Закрити',
  allowCamera: 'Увімкніть камеру, будь ласка',
  allow: 'Дозволити',
  arrorAddingCard: 'Помилка додавання карти',
  howParkText: 'Ми прагнемо підтримувати місто чистим і охайним. Ми просимо вас зробити те ж саме і підтвердити це, сфотографувавши свою парковку. Не блокуйте шляхи, під’їзди чи велосипедні доріжки. Намагайтеся припаркуватися біля стоянок для велосипедів або спеціально відведених паркувальних місць, намальованих на вулиці. Часте порушення наших правил паркування призводить до стягнення додаткової плати або навіть деактивації вашого облікового запису.',
  inputPhoneNumber: 'Введіть номер телефону',
  invalidPhoneNumber: 'Невірний номер',
  continue: 'Продовжити',
  continueWith: 'Або продовжити через',
  terms: 'Якщо ви створюєте новий обліковий запис, ви автоматично погоджуєтеся з Умовами використання та захисту персональних даних',
  enterSms: 'Введіть код із SMS підтвердження',
  sentSms: 'Ми відправили СМС-код підтвердження на номер',
  resendCodeIn: 'Повторно надіслати код через',
  resendCode: 'Надіслати код повторно',
  resendSmsCode: 'Повторно надіслати SMS-код',
  requestCall: 'Надіслати на телефон',
  changePhoneNumber: 'Змінити номер телефону',
  invalidSms: 'Невірний код',
  tellAboutYou: 'Розкажіть щось про себе',
  whatsYourName: 'Як вас звати?',
  name: 'Ім`я',
  surname: 'Прізвище',
  incorrectName: 'Ім\'я, яке ви ввели, було неправильним',
  incorrectSurName: 'Ви ввели неправильне прізвище',
  enterEmail: 'Введіть адресу електронної пошти',
  enterValidEmail: 'Будь ласка, введіть дійсну адресу електронної пошти',
  invalidEmail: 'Введена вами електронна адреса недійсна',
  ageSure: 'Ми повинні бути впевнені у віці',
  must18: 'Користуватися самокатами можна лише з 18 років',
  able18: 'Вам має бути принаймні 18 років, щоб мати змогу їздити по місту.',
  loading: 'Завантаження',
  addPaymentCard: 'Додайте платіжну картку',
  cardNumber: 'Номер картки',
  expiryDate: 'Термін придатності',
  cvv: 'CVV',
  safetyComesFirst: 'Безпека на першому місці',
  noScooterExperience: 'Якщо у вас немає досвіду роботи з електросамокатами, рекомендуємо вибрати режим «Початківець» з обмеженою швидкістю. Ви можете будь-коли скинути це налаштування до значення за замовчуванням 25 км/год у Центрі безпеки.',
  beginner: 'Початківець',
  limitSpeed15: 'Обмеження швидкості до 15 км/год',
  notNow: 'Не зараз',
  safetyCenter: 'Центр безпеки',
  setPreferences: 'Визначте свої вподобання та отримуйте поради щодо безпечного водіння!',
  scan: 'Сканувати',
  turnOnLocation: 'Увімкніть своє місцезнаходження',
  withoutLocation: 'Без активної геолокації функціональні програми не будуть повноцінними',
  iUnderstand: 'Я розумію',
  withoutAccessToFiles: 'Без доступу до файлів програма працювати не буде',
  freeRide: 'Безкоштовний проїзд!',
  checkPromoForFreeRide: 'Перевірте свою акцію на безкоштовну поїздку',
  weAreNotInCity: 'О, ми ще не у вашому місті!',
  preparingToLaunchServiceInCity: 'Ми тільки готуємось запустити послугу у вашому місті. Ми повідомимо вас, коли це зміниться!',
  becomePartner: 'Стати партнером',
  connectionLost: 'Зв\'язок втрачено. Спробуйте знову.',
  wantKnowMoreAboutGettingStarted: 'Я хочу дізнатися більше про початок роботи',
  safetyTips: 'Поради з безпеки',
  learnMoreAboutRoadSafety: 'Дізнайтеся більше про безпеку на дорозі',
  localRules: 'Місцеві правила',
  learnMoreAboutLocalRequirements: 'Дізнайтеся більше про місцеві вимоги',
  privateRide: 'Приватна поїздка',
  corporateRide: 'Корпоративна поїздка',
  reserve: 'Резерв',
  unlock: 'Розблокувати',
  reserveFor: 'Резерв для',
  canReserveScooterForMinutes: 'Ви можете забронювати скутер на',
  canReserveScooterForMinutes2: 'Оплата почнеться, як тільки ви підтвердите бронювання.',
  confirmReservation: 'Підтвердити бронювання',
  reservationOngoing: 'Бронювання триває',
  cancelReservation: 'Скасувати бронювання',
  reservationCanceled: 'Бронювання скасовано',
  reservationTimedOut: 'Час очікування бронювання минув',
  reserveAgain: 'Резервувати знову',
  addCard: 'Додати картку',
  skip: 'Пропустити',
  beforeYourRide: 'Перед поїздкою',
  enterYourCardDetails: 'Введіть дані картки, щоб розпочати поїздку.',
  drivingInProhibitedZone: 'Ви потрапили в зону обмеженого доступу. Тут ви не знайдете місця для паркування',
  dangerDriving: 'Проїзд в забороненій зоні',
  prohibitedZone: 'Заборонена зона!',
  endRide: 'Кінець їзди',
  startRide: 'Почати поїздку',
  thisIsParkingZone: 'Це зона паркування',
  parkingAreaLook: 'Тут ви можете побачити, як виглядає паркінг. Будь ласка, знайдіть один поруч.',
  goParkingZone: 'Іди в зону паркування!',
  endRideParkingZones: 'Завершити поїздку можна лише у визначених зонах паркування.',
  enterCodeManually: 'Введіть код вручну',
  scanError: 'Помилка сканування. Будь ласка спробуйте ще раз.',
  enterCodeToUnlock: 'Введіть код для розблокування',
  scooterReadyEnterCode: 'Скутер готовий! Введіть код (код на кермі)',
  invalidCode: 'Невірний код, спробуйте ще раз.',
  activeRide: 'Активна їзда',
  slowZone: 'Повільна зона',
  pauseRide: 'Призупинити поїздку?',
  pauseTemporarilyLock: 'Пауза тимчасово заблокує самокат, щоб ви могли продовжити поїздку пізніше. Швидкість паузи застосовується на час блокування.',
  pause: 'Пауза',
  connectionError: 'Помилка з\'єднання',
  parkingZone: 'Зона паркування',
  PausedRide: 'Призупинено поїздку',
  continueWithRide: 'Продовжити поїздку',
  checkScooter: 'Перевірте скутер',
  scooterOnKickstand: 'Самокат стоїть на підставці',
  scooterNotObstruct: 'Скутер не заважає велосипедистам, під’їздам чи дорогам',
  takePictureScooter: 'Сфотографуйте скутер',
  howPark: 'Як паркуватися?',
  watchOutParking: 'Слідкуйте за паркуванням!',
  yourRideHasEnded: 'Ваша поїздка закінчилася',
  pickUp: 'Початок їзди',
  badRide: 'Погана їзда',
  goodRide: 'Хороша поїздка',
  reportProblem: 'Повідомити про проблему',
  somethingIsWrong: 'Щось не так? Давайте розглянемо це разом. Про що проблема?',
  parking: 'Паркінг',
  scooter: 'Скутер',
  accident: 'ДТП',
  app: 'Додаток',
  contactUs: 'Зв\'яжіться з нами',
  parkingProblems: 'Проблеми з паркуванням',
  tellMoreAboutIssue: 'Розкажіть нам трохи більше про проблему…',
  scooterIsNotHere: 'Скутера тут немає',
  scooterParkedIncorrectly: 'Скутер неправильно припаркований',
  scooterBlockingTraffic: 'Скутер блокує рух',
  others: 'Інші',
  scooterNotWorkingTellAboutIssue: 'Скутер не працює? Розкажіть нам трохи більше про проблему…',
  scooterDamaged: 'Скутер подряпаний або пошкоджений',
  scooterTechnicalIssue: 'У скутера технічна проблема',
  scooterTooSlow: 'Скутер занадто повільний',
  appSaysScooterOffline: 'Додаток каже, що скутер офлайн',
  scooterNotResponding: 'Скутер не реагує',
  scooterDoesntStart: 'Скутер не заводиться',
  scooterLayingGround: 'Скутер лежить на землі',
  accidentHappenedTellAboutIssue: 'Сталася аварія? Розкажіть нам трохи більше про проблему…',
  iInvolvedInAccident: 'Я потрапив у ДТП',
  iDamagedScooter: 'Я подряпав / пошкодив скутер',
  appNotWorkTellAboutIssue: 'Додаток не працює належним чином? Розкажіть нам трохи більше про проблему…',
  unableStartTrip: 'Неможливо розпочати подорож',
  unableEndTrip: 'Не вдалося завершити поїздку',
  myAccountBlocked: 'Мій обліковий запис заблоковано',
  appCrashing: 'Додаток зависає або виходить з ладу',
  cantAddCard: 'Я не можу додати картку',
  reportDamage: 'Повідомити про пошкодження',
  takePictureDamage: 'Сфотографуйте пошкодження',
  yourComment: 'Ваш коментар (обов\'язково)',
  enterProblemHere: 'Введіть свою проблему тут…',
  goToProfile: 'Перейти в профіль',
  payment: 'Оплата',
  promoCodes: 'Промо коди',
  freeMinutes: 'Безкоштовні хвилини',
  minutes:'хвилин',
  claim: 'Отримай',
  history: 'Історія',
  support: 'Підтримка',
  partnership: 'Партнерство',
  rewards: 'Нагороди',
  personalInfo: 'Особиста інформація',
  necessaryInfo: 'Необхідна інформація',
  termsService: 'Умови обслуговування',
  personalDataProtectionPolicy: 'Політика захисту персональних даних',
  aboutApplication: 'Про застосування',
  areYouSureAboutChanges: 'Ви впевнені в змінах?',
  problemWeCantSolveContactSupport: 'У вас є проблема, яку ми не можемо вирішити в додатку? Зверніться до нашої служби підтримки',
  questionsAndAnswers: 'Питання та відповіді',
  safety: 'Безпека',
  phone: 'Телефон',
  chat: 'Чат',
  tellProblem: 'Розкажіть про проблему',
  haveProblemTakeLookFAQ: 'У вас є проблема чи питання? Перегляньте FAQ.',
  historyOfRides: 'Історія атракціонів',
  historyOfPromoCodes: 'Історія промокодів',
  scooterWillSlowDown: 'Ваш скутер сповільниться і може повністю зупинитися. Ви не можете завершити свою поїздку тут. Будь ласка, знайдіть місце для паркування.',
  thankForRegistration: 'Дякуємо за реєстрацію. У нас для вас є подарунок!',
  welcomeToSvist: 'Ласкаво просимо до Свіст! Дотримуйтеся підручника, щоб навчитися їздити на самокаті.',
  exit: 'Вихід'

}
export const sk = {
  km:'kil',
  min:'min',
  back:'Späť',
  jan: 'jan',
  fab: 'fab',
  march: 'march',
  apr: 'apr',
  may: 'máj',
  june: 'jún',
  july: 'júl',
  aug: 'aug',
  sep: 'sep',
  oct: 'okt',
  nov: 'nov',
  dec: 'dec',
  noRide:'Žiadna jazda',
  fillEmail:'Vyplňte e-mail',
  hour:'hod',
  negativeBalance: 'Záp. zostatok',
  error: 'Chyba',
  close: 'Zavrieť',
  allowCamera: 'Zapnite fotoaparát, prosím',
  allow: 'Povoliť',
  arrorAddingCard: 'Chyba pri pridávaní mapy',
  howParkText: 'Zaviazali sme sa udržiavať mesto čisté a upratané. my požiadajte vás, aby ste urobili to isté a overte si to odfotením vášho parkovania. Neblokujte cesty, vchody alebo cyklistické pruhy. Skúste zaparkovať v blízkosti stojanov na bicykle alebo určených parkovacích plôch namaľovaných na ulici. Časté porušenie našich smerníc o parkovaní bude mať za následok príplatok alebo dokonca deaktiváciu vášho parkovania účtu.',
  inputPhoneNumber: 'Zadaj telefónne číslo',
  invalidPhoneNumber: 'Неважећи број',
  continue: 'Pokračuj',
  continueWith: 'Pokračovať s ',
  terms: 'Pokiaľ si zakladáš nový účet, automaticky súhlasíš s Podmienkami používania a Ochranou osobných údajov',
  enterSms: 'Zadaj kód z potvrdzovacej SMS',
  sentSms: 'Na telefónne číslo sme ti práve odoslali SMS s potvrdzovacím kódom',
  resendCodeIn: 'Znovu zaslať kód o',
  resendCode: 'Znovu zaslať kód',
  resendSmsCode: 'Znovu zaslať kód pomocou SMS ',
  requestCall: 'Požiadať o zavolanie',
  changePhoneNumber: 'Upraviť telefónne číslo',
  invalidSms: 'Zadaný kód nie je správny',
  tellAboutYou: 'Povedz nám niečo o sebe',
  whatsYourName: 'Ako sa voláš?',
  name: 'Meno',
  surname: 'Priezvisko',
  incorrectName: 'Chybné meno',
  enterEmail: 'Zadaj svoj e-mail',
  enterValidEmail: 'Pre úspešné dokončenie registrácie zadaj platnú e-mailovú adresu',
  invalidEmail: 'Zadaný e-mail je nesprávný',
  ageSure: 'Musíme si byť istí vekom',
  must18: 'Kolobežky môžete používať, len ak máte 18+ rokov',
  able18:'Aby si mohol/mohla svišťať mestom, musíš mať aspoň 18 rokov.',
  loading: 'Svištííííííííím',
  addPaymentCard: 'Vlož platobnú kartu',
  cardNumber: 'Číslo karty',
  expiryDate: 'Platnosť karty',
  cvv: 'CVV kód',
  safetyComesFirst: 'Bezpečnosť na prvom mieste',
  noScooterExperience: 'Pokiaľ si v jazde na elektrických kolobežkách začiatočník a nemáš ešte dostatok skúseností, odporúčame ti zvoliť mód “Baby Svišť”.',
  beginner: 'Začiatočník',
  limitSpeed15: 'Obmedziť rýchlosť na 15 km/h',
  notNow: 'Teraz nie',
  safetyCenter: 'Centrum bezpečnosti',
  setPreferences: 'Nastav si preferencie a získaj tipy na bezpečnú jazdu!',
  scan: 'Naskenovať',
  turnOnLocation: 'Zapnúť sledovanie polohy',
  withoutLocation: 'Bez aktívnej geolokácie funkčné aplikácie nebudú kompletné',
  iUnderstand: 'Rozumiem',
  withoutAccessToFiles: 'Zapnúť sledovanie polohy',
  freeRide: 'Jazda zadarmo!',
  claim: 'Nárokovať si',
  checkPromoForFreeRide: 'Čekni sekciu promo kódov pre ďalšie výhody.',
  weAreNotInCity: 'Och nie, v tvojom meste ešte nesvištíme! :( ',
  preparingToLaunchServiceInCity: 'Spustenie služby ešte len pripravujeme. Akonáhle sa to zmení, dáme ti vedieť!',
  becomePartner: 'Stať sa partnerom',
  connectionLost: 'Pripojenie nesviští :( Skús to znovu.',
  wantKnowMoreAboutGettingStarted: 'Chcem vedieť viac o začatí jazdy',
  safetyTips: 'Tipy pre bezpečnosť',
  learnMoreAboutRoadSafety: 'Dozvedieť sa viac o bezpečnosti na cestách',
  localRules: 'Miestne pravidlá',
  learnMoreAboutLocalRequirements: 'Dozvedieť sa viac o požiadavkách mesta',
  privateRide: 'Svištím súkromne ',
  corporateRide: 'Svištím na firmu',
  reserve: 'Rezervovať',
  unlock: 'Odomknúť',
  reserveFor: 'Rezervované na',
  canReserveScooterForMinutes: 'Kolobežku si môžeš rezervovať na',
  canReserveScooterForMinutes2: 'Účtovať sa začne akonáhle potvrdíš rezerváciu.',
  confirmReservation: 'Potvrdiť rezerváciu',
  reservationOngoing: 'Prebieha rezervácia',
  cancelReservation: 'Zrušiť rezerváciu',
  reservationCanceled: 'Rezervácia zrušená',
  reservationTimedOut: 'Čas rezervácie vypršal',
  reserveAgain: 'Znova rezervovať',
  addCard: 'Pridať kartu',
  skip: 'Preskočiť',
  beforeYourRide: 'Predtým než posvištíš',
  enterYourCardDetails: 'Ak chceš svišťať, zadaj údaje o svojej karte.',
  drivingInProhibitedZone: 'Vstúpili ste do zakázanej zóny. Parkovacie miesto tu nenájdete',

  dangerDriving:'Jazda v zakázanej zóne.',
  prohibitedZone: 'Zakázaná zóna!',
  endRide: 'Ukončiť jazdu',
  startRide: 'Začnite jazdu',
  thisIsParkingZone: 'Parkovacia zóna',
  parkingAreaLook: 'Tu vidíš hranice parkovacej zóny. Dosvišti do nej, prosím!',
  goParkingZone: 'Choď do parkovacej zóny! ',
  endRideParkingZones: 'Jazdu môžeš ukončiť len vo vyznačených parkovacích zónach.',
  enterCodeManually: 'Vložiť kód ručne',
  scanError: 'Ups, chyba pri skenovaní! Skús to znova.',
  enterCodeToUnlock: 'Vlož kód pre odomknutie',
  scooterReadyEnterCode: 'Kolobežka je pripravená! Vlož kód (kód je napísaný na riadidlách)',
  invalidCode: 'Ajaj, neplatný kód! Skús to znova',
  activeRide: 'Svištíš!',
  slowZone: 'Pomalá zóna',
  pauseRide: 'Pozastaviť jazdu?',
  pauseTemporarilyLock: 'Pozastavenie jazdy dočasne uzamkne kolobežku, takže budeš môcť svišťať neskôr. Poplatok za pauzu je aplikovaná po dobu uzamknutia',
  pause: 'Dočasne uzamknúť',
  connectionError: 'Pripojenie nesviští :(',
  parkingZone: 'Parkovacia zóna',
  PausedRide: 'Pozastavená jazda',
  continueWithRide: 'Pokračovať v jazde',
  checkScooter: 'Skontroluj kolobežku',
  scooterOnKickstand: 'Kolobežka je na stojane',
  scooterNotObstruct: 'Kolobežka nebráni cyklistom ani chodcom a neprekáža na cestách.',
  takePictureScooter: 'Vyfoť kolobežku',
  howPark: 'Ako zaparkovať? ',
  watchOutParking: 'Pozor na to ako parkuješ!',
  yourRideHasEnded: 'Juhuu, dosvišťal si do cieľa!',
  pickUp: 'Vyzdvihnutie',
  badRide: 'Nič moc jazda ',
  goodRide: 'Cool jazda ',
  reportProblem: 'Nahlásiť problém',
  somethingIsWrong: 'Niečo nebolo v poriadku? Poďme sa na to spoločne pozrieť. Čoho sa problém týka?',
  parking: 'Parkovanie',
  scooter: 'Kolobežka',
  accident: 'Nehoda',
  app: 'Aplikácia',
  contactUs: 'Kontaktuj nás',
  parkingProblems: 'Problémy s parkovaním',
  tellMoreAboutIssue: 'Povedz nám o probléme trochu viac…',
  scooterIsNotHere: 'Kolobežka tu nie je',
  scooterParkedIncorrectly: 'Kolobežka je zaparkovaná nesprávne',
  scooterBlockingTraffic: 'Kolobežka blokuje premávku',
  others: 'Iné',
  scooterNotWorkingTellAboutIssue: 'Kolobežka nesviští? Povedz nám o probléme trochu viac…',
  scooterDamaged: 'Kolobežka je poškriabaná alebo poškodená',
  scooterTechnicalIssue: 'Kolobežka má technický problém',
  scooterTooSlow: 'Kolobežka je príliš pomalá',
  appSaysScooterOffline: 'Aplikácia hovorí/ukazuje, že je kolobežka offline',
  scooterNotResponding: 'Kolobežka nereaguje',
  scooterDoesntStart: 'Kolobežka nechce naštartovať',
  scooterLayingGround: 'Kolobežka leží na zemi',
  accidentHappenedTellAboutIssue: 'Došlo k zrážke? Povedz nám o probléme trochu viac…',
  iInvolvedInAccident: 'Bol/a som účastníkom nehody',
  iDamagedScooter: 'Poškriabal/a som alebo poškodil/a kolobežku',
  appNotWorkTellAboutIssue: 'Appka nesviští ako by mala? Povedz nám o probléme trochu viac…',
  unableStartTrip: 'Nejde začať jazdu',
  unableEndTrip: 'Nejde ukončiť jazdu',
  myAccountBlocked: 'Môj účet je zablokovaný',
  appCrashing: 'Appka zamŕza alebo vypadáva',
  cantAddCard: 'Nemôžem pridať kartu',
  reportDamage: 'Nahlásiť poškodenie',
  takePictureDamage: 'Odfotiť poškodenie',
  yourComment: 'Tvoj komentár',
  enterProblemHere: 'Tu zadajte svoj problém…',
  goToProfile: 'Prejsť na profil',
  payment: 'Platba',
  promoCodes: 'Promo kódy',
  freeMinutes: 'Voľné minúty',
  minutes:'minút',
  history: 'História',
  support: 'Podpora',
  partnership: 'Spolupráca',
  rewards: 'Odmeny',
  personalInfo: 'Osobné údaje',
  necessaryInfo: 'Potrebné informácie',
  termsService: 'Podmienky služby',
  personalDataProtectionPolicy: 'Zásady ochrany osobných údajov',
  aboutApplication: 'O aplikácii',
  areYouSureAboutChanges: 'Si si istý/á zmenami?',
  problemWeCantSolveContactSupport: 'Máš problém, ktorý v appke nevyriešime? Obrať sa na našu podporu. Pomôžeme ti skôr než stihneš povedať “SVIŠŤ”!',
  questionsAndAnswers: 'Otázky a odpovede',
  safety: 'Bezpečnosť',
  phone: 'Telefón',
  chat: 'Chat',
  tellProblem: 'Povedz nám, čo sa deje!',
  haveProblemTakeLookFAQ: 'Máš problém alebo otázku? Mrkni do FAQ.',
  historyOfRides: 'História jázd',
  historyOfPromoCodes: 'História promo kódov',
  scooterWillSlowDown: 'Vaša kolobežka sa spomalí a môže sa úplne zastaviť. Tu nemôžete svoju jazdu ukončiť. Nájdite parkovacie miesto.',
  thankForRegistration: 'Thank you for your registration. We have a present for you! ',
  welcomeToSvist: 'Welcome to Svist! Please follow the tutorial to learn how to ride our scooter.',
  exit: 'Výstup'

}
